use customer_behavior

select top 5 * from customer;

--Q1. What is the total revenue generated by male vs. female customers?
select gender,
		sum(purchase_amount)as total_revenue
from customer
group by gender


--Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes'
and purchase_amount >= (select AVG(purchase_amount) from customer);


--Q3. Which are the top 5 products with the highest average review rating?
select top 5
		item_purchased, 
		AVG(review_rating) as avg_rating
from customer
group by item_purchased
order by avg_rating desc;


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, AVG(purchase_amount)as avg_purchase
from customer
where shipping_type in ('Standard' , 'Express')
group by shipping_type;


--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,
		AVG(purchase_amount)as avg_spend,
		SUM(purchase_amount) as total_revenue
from customer
group by subscription_status;


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select top 5
		item_purchased,
		SUM(
			case
				when discount_applied = 'Yes' then 1 else 0
			end
		) * 100.0 / COUNT(*) as discount_percentage
from customer
group by item_purchased
order by discount_percentage desc;


--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

--SELECT
--    CASE
--        WHEN previous_purchases = 0 THEN 'New'
--        WHEN previous_purchases <= 5 THEN 'Returning'
--        ELSE 'Loyal'
--   END AS customer_segment,
--    COUNT(*) AS customer_count
--FROM customer
--GROUP BY customer_segment;

with segmented_customers as
(
	select
		case 
			when previous_purchases = 0 then 'New'
			when previous_purchases <= 5 then 'Returning'
			else 'Loyal'
		end as customer_segment
	from customer
)
select customer_segment,
		COUNT(*) as customer_count
from segmented_customers
group by customer_segment;



--Q8. What are the top 3 most purchased products within each category? 
with product_count as
(
	select category, item_purchased,
			count(*) as purchase_count
	from customer
	group by category, item_purchased
),

ranked_products as
(
	select *,
		ROW_NUMBER() over
		(
			partition by category
			order by purchase_count desc
		) as rank_no
	from product_count
)

select
	category,
	item_purchased,
	purchase_count
from ranked_products
where rank_no <= 3 ;


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
		COUNT(*) as customer_count
from customer
where previous_purchases >5
group by subscription_status;


--Q10. What is the revenue contribution of each age group? 
select age_group,
		SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;